set SECRETS ~/.config/sops/secrets.yaml
cd (git rev-parse --show-toplevel)

set KEYS (sops -d "$SECRETS" | yq -r 'keys | .[]')
set SSH (printf '%s\n' $KEYS | grep '^ssh_' | sed 's/^ssh_//' | jq -Rc . | jq -sc .)
set WG (printf '%s\n' $KEYS | grep '^wg_' | sed 's/^wg_//' | jq -Rc . | jq -sc .)
set GPG (printf '%s\n' $KEYS | grep '^gpg_' | sed 's/^gpg_//' | jq -Rc . | jq -sc .)

printf '%s\n' \
    '# Auto-generated by: task secrets:manifest' \
    '{' \
    "  ssh = builtins.fromJSON ''$SSH'';" \
    "  wg = builtins.fromJSON ''$WG'';" \
    "  gpg = builtins.fromJSON ''$GPG'';" \
    '}' > ops/secrets/manifest.nix

echo "Generated ops/secrets/manifest.nix"
