# Font
font_family JetBrainsMono Nerd Font
font_size 11

# Window
background_opacity 0.95

# Catppuccin Mocha
foreground #CDD6F4
background #1E1E2E
selection_foreground #1E1E2E
selection_background #F5E0DC

# Black
color0 #45475A
color8 #585B70

# Red
color1 #F38BA8
color9 #F38BA8

# Green
color2 #A6E3A1
color10 #A6E3A1

# Yellow
color3 #F9E2AF
color11 #F9E2AF

# Blue
color4 #89B4FA
color12 #89B4FA

# Magenta
color5 #F5C2E7
color13 #F5C2E7

# Cyan
color6 #94E2D5
color14 #94E2D5

# White
color7 #BAC2DE
color15 #A6ADC8

# Cursor
cursor #F5E0DC
cursor_text_color #1E1E2E

# URL
url_color #89B4FA

# Tab bar
active_tab_foreground #1E1E2E
active_tab_background #CDD6F4
inactive_tab_foreground #CDD6F4
inactive_tab_background #1E1E2E
