set SECRETS ~/.config/sops/secrets.yaml
cd (git rev-parse --show-toplevel)

set KEYS (sops -d "$SECRETS" | yq -r 'keys | .[]')
set SSH (echo "$KEYS" | grep '^ssh_' | sed 's/^ssh_//' | jq -R . | jq -s .)
set WG (echo "$KEYS" | grep '^wg_' | sed 's/^wg_//' | jq -R . | jq -s .)
set GPG (echo "$KEYS" | grep '^gpg_' | sed 's/^gpg_//' | jq -R . | jq -s .)

printf '%s\n' \
    '# Auto-generated by: task secrets:manifest' \
    '{' \
    "  ssh = builtins.fromJSON ''$SSH'';" \
    "  wg = builtins.fromJSON ''$WG'';" \
    "  gpg = builtins.fromJSON ''$GPG'';" \
    '}' > modules/secrets/manifest.nix

echo "Generated modules/secrets/manifest.nix"
