name: Setup Nix
description: Install Nix with extra caches

runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf-file: ${{ github.workspace }}/.github/nix-extra.conf

    - uses: DeterminateSystems/magic-nix-cache-action@main
