# Auto-generated by: go-task secrets:manifest
# Source of truth for all secrets - both nix and Taskfile read this
{
  ssh = builtins.fromJSON ''
    [
      "id_ed25519",
      "id_ed25519_3dpreview",
      "id_rsa",
      "ad_rsa",
      "id_site_packages",
      "id_site_packages_ed25519",
      "mrserver",
      "config",
      "id_ed25519.pub",
      "id_ed25519_3dpreview.pub",
      "id_rsa.ppk",
      "id_rsa.pub",
      "id_site_packages.pub",
      "id_site_packages_ed25519.pub"
    ]'';
  wg = builtins.fromJSON ''
    [
      "ddck_1",
      "sp_office_peer4",
      "sptest_peer3",
      "stuff_ipv6"
    ]'';
  gpg = builtins.fromJSON ''
    [
      "key_personal",
      "key_hotmail",
      "key_simplyprint"
    ]'';
}
